### ISSUE TITLE
Question about get_inlier_grasp_indices

### ISSUE THREAD

**Issue by bearpaw** [jsll/pytorch_6dof-graspnet#3]
Hi Jens,

I found that you use `get_inlier_grasp_indices` to filter out grasps that are far away from the center of the object. I didn't find the similar function in the original tf version code. Is this what you add in this repo?

Also, you use the `pc_mean` as object center to compute the distance between the grasps and the object (
https://github.com/jsll/pytorch_6dof-graspnet/blob/master/grasp_estimator.py#L62). However, the grasps are computed with the normalized pointcloud, which means the center of the "normalized" object is `(0, 0, 0)`. So I feel you should use `(0, 0, 0)` instead of `pc_mean` when you call the `get_inlier_grasp_indices`. Can you verify whether it is a bug? Thanks.

**Comment by jsll** [comment]
Hi,

> I found that you use get_inlier_grasp_indices to filter out grasps that are far away from the center of the object. I didn't find the similar function in the original tf version code. Is this what you add in this repo?

Yes I added this function mainly for visualization. The problems was that if the generator generated a grasp that was far from the object the visualization window zoomed out such that the outlier grasp was visible. Therefore I added the `get_inlier_grasp_indices`.

> Also, you use the pc_mean as object center to compute the distance between the grasps and the object (
https://github.com/jsll/pytorch_6dof-graspnet/blob/master/grasp_estimator.py#L62). However, the grasps are computed with the normalized pointcloud, which means the center of the "normalized" object is (0, 0, 0). So I feel you should use (0, 0, 0) instead of pc_mean when you call the get_inlier_grasp_indices. Can you verify whether it is a bug? Thanks.

You are correct about this that it was a bug. However, it has worked fine as apparently the `pc_mean` happens to be very close to (0,0,0). Nevertheless I will fix this issue. Thanks for spotting it :)

**Comment by jsll** [comment]
@bearpaw I fixed this now and will close this issue.
